name: CI
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-python
        with:
          path: . 
          generate-lock: true

      - name: Install virtual env
        run:  make .venv
      - name: Check formatting
        run:  make check-fmt
      - name: Check linting
        run:  make check-linter
      - name: Check typing
        run:  make check-typing
      - name: Run tests
        run:  make test
      - name: Build sdist
        run:  make sdist
      - name: Build dist
        run:  make dist
