
name: Publish package to PyPI

on:
  push:
    branches:
      - main
    paths:
      - VERSION_NUMBER

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ocean-spark-airflow-provider
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.7.1"

      - name: poetry build
        run: make build
        shell: bash

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
